# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js 18 image as a base
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json tsconfig.json /app/

# Install dependencies
RUN npm install --ignore-scripts

# Copy the source code
COPY src /app/src

# Compile TypeScript to JavaScript
RUN npm run build

# Use a minimal node image for the production environment
FROM node:18-alpine AS release

# Set the working directory
WORKDIR /app

# Copy the compiled output and package files from the builder
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json

# Install only production dependencies
RUN npm ci --omit=dev

# Define the environment variables (these should be provided at runtime or via a .env file)
ENV GHOST_URL="https://your-ghost-blog.com"
ENV GHOST_ADMIN_API_KEY="your_admin_api_key"

# Expose the port (if necessary, depends on MCP server implementation)
EXPOSE 8080

# Command to run the server
ENTRYPOINT ["node", "build/index.js"]
